
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
Subscribe to see which companies asked this question

*/

var findTheDifference = function(s, t) {
	var A = [] , B = [];
	A = preProcess(s);
	B = preProcess(t);
	return (compare(A , B));
};

function compare( A , B ){
	var len = (A.length >= B.length)? A.length : B.length;
	for(var i=0 ; i<len ; i++){
		if( A[i] !== B[i] ){
			return B[i];
		}
	}
}

function preProcess(s){
	var str = s.split('').sort(function(a,b){
		return a.localeCompare(b);
	});
	return str;
}